# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-05-16 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('total_count', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_method', models.SmallIntegerField(choices=[(1, 'Cash on Delivery'), (2, 'Wechat'), (3, 'Alipay'), (4, 'UnionPay'), (5, 'PayPal')], default=1)),
                ('status', models.SmallIntegerField(choices=[(1, 'Completed')], default=1)),
                ('addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Address', verbose_name='address')),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Passport')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'order',
                'db_table': 's_order_info',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderInfo')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Products')),
            ],
            options={
                'db_table': 's_order_products',
            },
        ),
    ]
