# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-05-16 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=128, verbose_name='describe')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
                ('detail', tinymce.models.HTMLField()),
                ('image', models.ImageField(upload_to='products')),
                ('status', models.SmallIntegerField(choices=[(1, 'ONLINE'), (0, 'OFFLINE')], default=1)),
            ],
            options={
                'verbose_name': 'shelves',
                'verbose_name_plural': 'shelves',
                'db_table': 's_products',
            },
        ),
        migrations.CreateModel(
            name='ProductsType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='typelogo', verbose_name='LOGO')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'types',
                'verbose_name_plural': 'types',
                'db_table': 's_productstype',
                'ordering': ['c_time'],
            },
        ),
        migrations.AddField(
            model_name='products',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductsType'),
        ),
    ]
